model:
  path: "models/best_model.pt"  # Path to saved model
  metadata_path: "models/metadata.json"  # Path to model metadata
  type: "NeuralCollaborativeFiltering"  # Options: MatrixFactorizationModel, NeuralCollaborativeFiltering, TransformerRecommender

data:
  movies_path: "../data/movielens/ml-latest-small/movies.csv"
  ratings_path: "../data/movielens/ml-latest-small/ratings.csv"

server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 4

inference:
  batch_size: 128
  top_k: 10  # Number of recommendations to return

monitoring:
  prometheus_metrics: true
  log_level: "INFO"
```